before_script:
  - "npm ci react-scripts"
cache:
  directories:
    - node_modules
language: node_js
script: "npm run build"
node_js:
        - "stable"
    


branches:
  only:
    - master
    
notifications:
  email: false
sudo: required

